alias youtube='start chrome youtube.com'
alias netflix='start chrome https://netflix.com/browse'
alias facebook='start chrome facebook.com'
alias linkedin='start chrome linkedin.com/feed/'
alias gh='start chrome github.com'
alias sof='start chrome stackoverflow.com'
